# Generated by Django 3.2.15 on 2022-08-20 23:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dental_clinic', '0002_alter_record_specialist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recorddetail',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dental_clinic.appointment'),
        ),
        migrations.AlterField(
            model_name='recorddetail',
            name='date',
            field=models.DateField(),
        ),
    ]
