# Generated by Django 3.2.15 on 2022-08-22 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dental_clinic', '0003_auto_20220820_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='time',
            field=models.TimeField(default='00:00:00'),
            preserve_default=False,
        ),
    ]
