# Generated by Django 3.2.15 on 2022-08-22 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dental_clinic', '0004_appointment_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='recorddetail',
            name='cost',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
