# Generated by Django 3.2.15 on 2022-08-22 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dental_clinic', '0005_recorddetail_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recorddetail',
            name='appointment',
        ),
    ]
