# Generated by Django 3.2.15 on 2022-08-22 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dental_clinic', '0006_remove_recorddetail_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='recorddetail',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
